#!/usr/bin/env php
<?php

// Composer autoload.
require __DIR__ . '/vendor/autoload.php';

use Dotenv\Dotenv;
use DirkOlbrich\Stockfighter\Stockfighter;

// load .env
$dotenv = new Dotenv(__DIR__);
$dotenv->load();

// load the stockfighter app
$sf = new Stockfighter($_ENV['API_KEY']);

// $level = 'first_steps';
$level = 'chock_a_block';


// var_dump($sf->heartbeat());
echo "Starting Game\n";
$sf->gameStart($level);
usleep(4000000);
echo "Buying Order \n";
$sf->buy(10000, 10000, 'limit');
echo "Selling Order \n";
$sf->sell(10000, 10000, 'limit');

$orderbook = $sf->orderbook;
echo "Orders:\n";
foreach ($orderbook->orders as $order) {
    echo $order->direction . " | Price " . $order->price;
    echo " | Qty " . $order->originalQty . " | Fiiled " . $order->totalFilled . "\n";
}

$openOrders = $sf->orderbook->open();
usleep(10000000);

echo "Canceling Order \n";
foreach ($openOrders as $order) {
    $sf->cancelOrder($order->orderId);
}

$account = $sf->account;
echo "Balance: " . $account->balance. "\n";
foreach ($account->inventory as $pos) {
    echo "Stock " . $pos->stock . " | Qty " . $pos->qty . " | Avg Price " . $pos->avgPrice . "\n";
}
foreach ($account->transactions as $trans) {
    echo $trans->direction . " | Qty " . $trans->qty . " | Price " . $trans->price . "\n";
}


// for ($i=0; $i<100; $i++) {
//     // $quote = $sf->venue()->stock()->quote();
//     $orderbook = $sf->venue()->stock()->orderbook();
//     // var_dump($orderbook);
//     $bids = isset($orderbook->bids) ? $orderbook->bids : null;
//     $asks = isset($orderbook->asks) ? $orderbook->asks : null;

//     if ($bids) {
//         array_reverse($bids);
//         foreach ($bids as $bid) {
//             echo "Bid: " . $bid->price . " | Qty: " . $bid->qty . "\n";
//         }
//         $highestBid = $bids[0]->price;
//         var_dump($sf->venue()->stock()->buy(
//             $highestBid + floor($highestBid * 0.01),
//             rand(9000, 11000),
//             'immediate-or-cancel'
//         ));
//     }

//     usleep(2000000);
// }

?>
